server:
  port: 8088
spring:
  application:
    name: lab05
  datasource:
      url: jdbc:mysql://localhost:3306/lab05
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      format_sql: true
    generate-ddl: true
    show-sql: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: thienni198@gmail.com
    password: qunt csvp cvcl tcys
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    protocol: smtp
api:
  prefix: /api/v1


logging:
  level:
    org:
      springframework.security: DEBUG