server:
  port: 8088
spring:
  application:
    name: lab05
  datasource:
      url: jdbc:mysql://localhost:3306/lab05
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true
    generate-ddl: true
    show-sql: true

api:
  prefix: /api/v1

logging:
  level:
    org:
      springframework.security: DEBUG